/** Public German URLs. Sitemap generation and prerender both read this list. */
export const routes = [
  { path: "/", changefreq: "weekly", priority: "1.0" },
  { path: "/leistungen", changefreq: "monthly", priority: "0.9" },
  { path: "/leistungen/empfang", changefreq: "monthly", priority: "0.8" },
  { path: "/leistungen/night-audit", changefreq: "monthly", priority: "0.8" },
  { path: "/leistungen/tagung", changefreq: "monthly", priority: "0.8" },
  { path: "/leistungen/seminar-support", changefreq: "monthly", priority: "0.8" },
  { path: "/leistungen/buero-empfang", changefreq: "monthly", priority: "0.8" },
  { path: "/einsatzgebiet", changefreq: "monthly", priority: "0.9" },
  { path: "/einsatzgebiet/frankfurt", changefreq: "monthly", priority: "0.8" },
  { path: "/einsatzgebiet/flughafen-frankfurt", changefreq: "monthly", priority: "0.8" },
  { path: "/einsatzgebiet/offenbach", changefreq: "monthly", priority: "0.8" },
  { path: "/einsatzgebiet/taunus", changefreq: "monthly", priority: "0.8" },
  { path: "/einsatzgebiet/wiesbaden", changefreq: "monthly", priority: "0.8" },
  { path: "/einsatzgebiet/mainz", changefreq: "monthly", priority: "0.8" },
  { path: "/einsatzgebiet/darmstadt", changefreq: "monthly", priority: "0.8" },
  { path: "/einsatzgebiet/neu-isenburg", changefreq: "monthly", priority: "0.8" },
  { path: "/einsatzgebiet/hanau", changefreq: "monthly", priority: "0.8" },
  { path: "/ueber-uns", changefreq: "monthly", priority: "0.8" },
  { path: "/karriere", changefreq: "monthly", priority: "0.8" },
  { path: "/karriere/empfangskraft", changefreq: "monthly", priority: "0.7" },
  { path: "/karriere/night-auditor", changefreq: "monthly", priority: "0.7" },
  { path: "/kontakt", changefreq: "monthly", priority: "0.8" },
  { path: "/impressum", changefreq: "yearly", priority: "0.3" },
  { path: "/datenschutz", changefreq: "yearly", priority: "0.3" },
];
